### ISSUE TITLE
Actualización de modelos

### ISSUE THREAD

**Issue by jjsanmartino03** [jjsanmartino03/gestion-luces#19]
Actualizar los modelos y realizar las migraciones para reflejar los cambios del DER:

![imagen](https://github.com/jjsanmartino03/gestion-luces/assets/58923155/f615c0c5-9e4d-4d8f-8b00-da404e6a59a8)

**Comment by LuciaKarlen** [comment]
Además, agregar fecha hasta que se pueda null
